Spinners and Loaders components
gsoft-inc/sg-orbit pull request #1184
Opened 2023-03-08 19:27 UTC by alexasselin008

## Summary
- A loader provides reassurance that content is currently being loaded, processing, or that change will occur on the page.
- A spinner indicates that a part of the product is currently loading or performing a task, and the duration of this process is unknown.

2023-03-08 22:16 UTC, patricklafrance requested changes

2023-03-08 22:16 UTC, patricklafrance commented on packages/components/src/input/src/useInputContent.tsx
> +    return loading && <Spinner className="o-ui-input-spinner" role="presentation" size="md" />;
Do you really need to specify size="md" ? It's the default size

2023-03-08 22:16 UTC, patricklafrance commented on packages/components/src/spinner/src/Spinner.tsx
> +                    role: "status"
I am puzzled by this one, it seems like the right role might "progressbar" according to React Aria progresse bar indeterminate example: https://react-spectrum.adobe.com/react-spectrum/ProgressCircle.html#indeterminate.

It kind of seems to make sense after reading the following https://www.digitala11y.com/progressbar-role.

If progress role is the right role, there be additional step taken in some of Orbits components to correctly set the `aria-describedby` and `aria-busy` attribute. The Spinner components documentation should also be updated to mention those.

How did you come up with the "status" role?

2023-03-08 22:22 UTC, patricklafrance commented on packages/components/src/spinner/docs/Spinner.stories.mdx
> +        <Inline alignY="end" backgroundColor="alias-accent" padding={4}>
Inline is not the right component here, you probably want Flex as you are not horizontally inlining multiple components

2023-03-08 22:22 UTC, patricklafrance commented on packages/components/src/spinner/docs/Spinner.stories.mdx
> +        <Inline alignY="end" backgroundColor="alias-accent" padding={4}>
In fact a regular Div might even be enough for this example

2023-03-08 22:23 UTC, patricklafrance commented on packages/components/src/spinner/src/Spinner.tsx
> +                        active && "active"
In which case would a spinner component not be active if he is rendered?

2023-03-09 14:40 UTC, alexasselin008 commented on packages/components/src/loader/src/Loader.tsx
> +                        active && "active"
show means the loader is visible. 
active means the loader is animated. We use this to disable animation for chromatic. We could use the disableAnimation to reduce the spinner's api

2023-03-09 14:46 UTC, alexasselin008 commented on packages/components/src/loader/src/Loader.tsx
> +        const showTimer = setTimeout(() => setShow(true), isNumber(delay) ? delay : DEFAULT_LOADER_DELAY);
Spinners are going to be widely use for all our network calls. I would expect the application devs to be able to choose if they want a longer or shorter delay, but most of the time I feel like people won't think about how long the delay should be. Providing a default options makes sense to me in that case. 

zendesk: 750ms
seek:  800ms
atlassian: 150-200 ms

I've been using 300ms in Home and Cloud Copy and it feels good. Most loading spinner aren't noticeable.

2023-03-09 16:52 UTC, alexasselin008 commented on packages/components/src/loader/tests/jest/Loader.test.tsx
> +test("ref is a DOM element", async () => {
The active props is already used by chromatic to disable the animation. As for the delay props, i've added two tests, but the only way to test that is to track the presence of a css class. Good enough, even if its not the most reliable way

2023-03-09 17:25 UTC, patricklafrance commented on packages/components/src/loader/src/Loader.tsx
> +        const showTimer = setTimeout(() => setShow(true), isNumber(delay) ? delay : DEFAULT_LOADER_DELAY);
Ok!

Then maybe the prop should be renamed to `delayed` ?

2023-03-09 17:26 UTC, alexasselin008 commented on packages/components/src/loader/src/Loader.tsx
> +        const showTimer = setTimeout(() => setShow(true), isNumber(delay) ? delay : DEFAULT_LOADER_DELAY);
Since its number or boolean, i'd keep delay

2023-03-09 17:36 UTC, patricklafrance commented on packages/components/src/loader/src/Loader.tsx
> +    const [show, setShow] = useState<boolean>(isNil(delay) || delay === false);
I don't think it should be named "show" as it's not a prop of the components API. It should be something like "isVisible" or even "isShow"

2023-03-14 20:52 UTC, fraincs approved these changes

2023-03-14 21:21 UTC, patricklafrance approved these changes

2023-03-15 00:08 UTC, merged